// This is a service worker file that will be processed by workbox-build
// We'll keep the import format since service workers use a different module system
// and this content gets injected into the final service worker file

import { precacheAndRoute } from 'workbox-precaching';
import { cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { clientsClaim } from 'workbox-core';

// This placeholder will be replaced by the list of files to precache generated by workbox-build
precacheAndRoute([{"revision":"c82563d43b1b25ce75965c3173c0501e","url":"404.html"},{"revision":"7df05e28e61562e79d973be8d5862301","url":"assets/index-D0k3xNci.js"},{"revision":"c79b5175b23af6526c2b2d6ac9f5aa5e","url":"assets/index-lQwI-_6l.css"},{"revision":"bb4e46b2fced0fcae0c46ed589f02d82","url":"favicon.svg"},{"revision":"0ecffe23bc31fed64225bd1110957070","url":"index.html"},{"revision":"7215ee9c7d9dc229d2921a40e899ec5f","url":"logo192.png"},{"revision":"7215ee9c7d9dc229d2921a40e899ec5f","url":"logo512.png"}]);
cleanupOutdatedCaches();

// Take control immediately on update so clients get the latest bundle (prevents “old UI on phone”)
self.skipWaiting();
clientsClaim();

// Example runtime caching (optional)
registerRoute(
  ({request}) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
}); 