// This is a service worker file that will be processed by workbox-build
// We'll keep the import format since service workers use a different module system
// and this content gets injected into the final service worker file

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// This placeholder will be replaced by the list of files to precache generated by workbox-build
precacheAndRoute([{"revision":"0974dbd1c156538d71e2bab0cc733ddf","url":"assets/index-BqU0VUXX.css"},{"revision":"4d1140626ce52a50a6551c85f568a142","url":"assets/index-wx4ZgJu8.js"},{"revision":"bb4e46b2fced0fcae0c46ed589f02d82","url":"favicon.svg"},{"revision":"741c480bf43775df080a349f7b11ad3d","url":"index.html"},{"revision":"7215ee9c7d9dc229d2921a40e899ec5f","url":"logo192.png"},{"revision":"7215ee9c7d9dc229d2921a40e899ec5f","url":"logo512.png"}]);

// Example runtime caching (optional)
registerRoute(
  ({request}) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
}); 