// This is a service worker file that will be processed by workbox-build
// We'll keep the import format since service workers use a different module system
// and this content gets injected into the final service worker file

import { precacheAndRoute } from 'workbox-precaching';
import { cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import { clientsClaim } from 'workbox-core';

// This placeholder will be replaced by the list of files to precache generated by workbox-build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Take control immediately on update so clients get the latest bundle (prevents “old UI on phone”)
self.skipWaiting();
clientsClaim();

// Example runtime caching (optional)
registerRoute(
  ({request}) => request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'images',
  })
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
}); 